name: Deploy specifications to GitHub pages

on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash
jobs:
  render-specs:
    uses: opencomputeproject/ocp-spec-tools/.github/workflows/render.yml@stable
    with:
      tcg-container-version: latest
      ocp-template-ref: stable
      inputs: >-
        [
          {
            "src": "doc/caliptra_20/Caliptra.ocp",
            "append_git_rev_to_version": true,
            "gh_pages_html": "2.0/specification/HEAD"
          },
          {
            "src": "doc/ocp_lock/lock_spec.ocp",
            "append_git_rev_to_version": true,
            "gh_pages_html": "ocp-lock/specification/HEAD",
            "gh_pages_pdf": "ocp-lock/specification/HEAD/pdf"
          }
        ]
      artifact-name: rendered-specs

  add-static-files:
    runs-on: ubuntu-latest
    name: Add static files
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Stage README
        run: |
          mkdir -p gh-pages-staging/doc
          cp -r doc/images/ gh-pages-staging/doc/
          cp README.md gh-pages-staging/README.md
          cp doc/Caliptra.md gh-pages-staging/doc/Caliptra.md
      - name: Build with jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: gh-pages-staging
          destination: gh-pages
      - name: Stage LOCK releases
        run: |
          mkdir -p gh-pages/ocp-lock/specification/
          cp doc/ocp_lock/OCP_LOCK_Specification_*.pdf gh-pages/ocp-lock/specification/
      - name: Upload artifacts for index
        uses: actions/upload-artifact@v4
        with:
          name: static-files
          path: gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [add-static-files, render-specs]
    steps:
      - name: Download static artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-files
          path: gh-pages
      - name: Download rendered artifacts
        uses: actions/download-artifact@v4
        with:
          name: rendered-specs
          path: gh-pages
      - name: Upload files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "gh-pages"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
